version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-backend
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    networks:
      - finance-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance-frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://backend:5000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - finance-net

networks:
  finance-net: